import delimited "/Users/jpmvbastos/Documents/GitHub/COVIDBR/Data/COVIDBR.csv", clear 

label var uf "State Abbrevation"
label var code "State code (IBGE)"
label var state "State name" 
label var stategdp "State GDP (in 2010 BRL), IPEADATA"
label var population "Total population, IPEADATA"
label var health_insurance "% of pop. with health insurance, IPEADATA"
label var hospitalbeds "Hospital beds per 10,000 people, OpenDataSUS"
label var icu "ICU beds per 10,000 people, OpenDataSUS"
label var population65 "% of population > 65yo, IPEADATA "
label var doctors  "Doctors per 10,000 people, OpenDataSUS"
label var gdp_pc "GDP per capita (in 2010 BRL), IPEADATA"
label var imlee "State Economic Freedom Score, Mackenzie Center"
label var lss "Lockdown Severity Score, Miozzi & Powell (2023)"
label var first_restriction "Date of first mandated restriction, OxCGRT"
label var first_stringency_index "Stringency at date of 1st mandated restriction, OxCGRT"
label var week_first_restriction "Week of first mandated restriction, OxCGRT"
label var deaths_week13 "Cum. Deaths at week 13, OpenDataSUS"
label var cases_week13 "Cum. Cases at week 13, OpenDataSUS"
label var first_death "Week of first death (=12 if before week 13), OpenDataSUS"
label var first_1kcases "Week reached 1,000 cum. cases, OpenDataSUS"
label var first_10cases_pc "Week reached 10 cases per 100k, OpenDataSUS"
label var first_100cases_pc "Week reached 100 cases per 100k, OpenDataSUS"
label var first_1death_pc "Week reached 1 death per 100k, OpenDataSUS"
label var first_10death_pc "Week reached 10 deaths per 100k, OpenDataSUS"
label var si2020 "Mean Stringency index score (2020), OxCGRT"
label var si2021 "Mean Stringency index score (2021), OxCGRT"
label var votes_left "Number of votes for Fernando Haddad (left)"
label var votes_right "Number of votes for Jair Bolsonaro (right)"
label var votes_null "Number of null votes (votos brancos e nulos)"
label var share_votes_right "Share of votes for Jair Bolsonaro"
label var deaths2020 "Total deaths (2020), OpenDataSUS"
label var deaths2021 "Total deaths (2021), OpenDataSUS"
label var cases2020 "Total cases (2020), Open Data SUS"
label var cases2021 "Total cases (2021), OpenDataSUS"
label var cases_pc2020 "Total cases per 100k (2020), OpenDataSUS"
label var cases_pc2021 "Total cases per 100k (2021), OpenDataSUS"
label var deaths_pc2020 "Total deaths per 100k (2020), OpenDataSUS"
label var deaths_pc2021 "Total deaths per 100k (2021), OpenDataSUS"

save "/Users/jpmvbastos/Documents/GitHub/COVIDBR/Data/COVIDBR.dta", replace

